# Site settings
title: ESAI
email: info@esai.info
description: > # this means to ignore newlines until "baseurl:"
  ESAI is an international, student-run, non-profit organization that aims to
  help Ethiopian students progress academically, improve the lives of Ethiopians,
  and create a networking environment between Ethiopian students and
  professionals.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: "@myESAi"
github_username:  myesai

# Build settings
markdown: kramdown
